name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install

    - name: Unit tests
      run: npm run test-unit

    - name: Check codestyle
      uses: reviewdog/action-eslint@v1.17
      with:
        reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
        fail_on_error: "true"
